### ISSUE TITLE
Add discord link to the repo

### ISSUE THREAD

**Issue by sansyrox** [sparckles/starfyre#26]

**Comment by ishaan1091** [comment]
I was trying this out, but when I opened the localhost:8000/public I saw that there was a lag between hello world being rendered and other parts of the page being rendered. Writing this here as wasn't able to find any community for the same.

Also I would like to contribute to this if there are some tasks with which I can help?

**Comment by sansyrox** [comment]
Hi @ishaan1091 , thank you for commenting. 

> but when I opened the localhost:8000/public I saw that there was a lag between hello world being rendered and other parts of the page being rendered

There is a rewrite in progress to address this issue.  (https://github.com/sansyrox/starfyre/pull/27)

Also, here is the discord link - https://discord.gg/uxPmKtCf

I look forward to seeing you there 😄

**Comment by sansyrox** [comment]
Completed!
