### ISSUE TITLE
Add a way to import css in the files

### ISSUE THREAD

**Issue by sansyrox** [sparckles/starfyre#44]
Ideally, we would want something like

```python
import './style.css'

def fx():
   ...
   
<pyml>

</pyml>
```

**Comment by SuelenKarbivnychyy** [comment]
@sansyrox I would like to work on this issue.

**Comment by SuelenKarbivnychyy** [comment]
@sansyrox Would you close this issue? Thank you :)

**Comment by sansyrox** [comment]
Fixed here - https://github.com/sparckles/starfyre/pull/56
