### ISSUE TITLE
Make the CLI interface smarter

### ISSUE THREAD

**Issue by sansyrox** [sparckles/starfyre#47]
Currently, we need to add exact paths in the cli. See this `python3 starfyre --dev=True --path="/Users/sanskar/repos/starfyre/test-application/" && python -m starfyre --build=True --path="/Users/sanskar/repos/starfyre/test-application/"`

Make this cli more human friendly. 

- remove the need to pass =True
- make this sequential invocation into a single command
- make the `--path` smarter

From our readme
```
Run the script `./build.sh`. This command will run the build process in starfyre against the test application in `test-application` directory.
  - The `build.sh` file is a simple script that runs two commands sequentially.
    - `python -m starfyre --dev=True --path="test-application/"`
    - `python -m starfyre --build=True --path="test-application/"`
        - The `path` variable here is the path to our application.
        - The `dev` flag here is used to start the compilation and create the `build` directory. 
        - The `build` directory is basically a python package that contains all the compiled files. We use the `--build` flag to run that package.
```

These both commands should be a single command by default.

**Comment by sansyrox** [comment]
More information regarding each points

- remove the need to pass=True
   - You need to specify `--dev=True` or `--build=True`. Ideally a good interface would be `python -m starfyre --dev`. i.e. if the flag is not passed then it is false, otherwise, it is true.
   - Also, we not should require to call two different commands - `--dev` and `--build`. We can merge them in a single command `python -m starfyre --build --path="test-application/"
   - Finally, we are having to specify a `/` at the end of the path, which is not ideal. We should also be defaulting the path variable to the current directory. So, strip the need to specify `/` at the end and default it to the current directory.

**Comment by DeleMike** [comment]
Thanks for more explanation.
