### ISSUE TITLE
Fix bug that got introduced while merging conflicts

### ISSUE THREAD

**Issue by SuelenKarbivnychyy** [sparckles/starfyre#63]
TypeError: RootParser.__init__() takes 5 positional arguments but 6 were given

**Comment by SuelenKarbivnychyy** [comment]
I'm working on it.

**Comment by DeleMike** [comment]
Nice, @SuelenKarbivnychyy ! It shouldn't be so.

Here look at this PR for why it increased to 6 parameters: https://github.com/sparckles/starfyre/pull/60/files/379215403f668d917ac9fc6a19423f14af5a8bd7

**Comment by SuelenKarbivnychyy** [comment]
> Nice, @SuelenKarbivnychyy ! It shouldn't be so.
> 
> Here look at this PR for why it increased to 6 parameters: https://github.com/sparckles/starfyre/pull/60/files/379215403f668d917ac9fc6a19423f14af5a8bd7

Yes, I used your PR to help me find out where I messed it up :D
