### ISSUE TITLE
Fix {use_parent_signal()} and {get_parent_signal()} to work properly

### ISSUE THREAD

**Issue by SuelenKarbivnychyy** [sparckles/starfyre#86]
Investigate why those functions are not working and fix it.

You can find they being used in parent.fyre file.

Screenshot of parent.fyre

![image](https://github.com/sparckles/starfyre/assets/109979645/f7d230c1-4d1d-440a-b366-aed1b3faa28b)

**Comment by sansyrox** [comment]
They are working now.
